'use client';
import { useEffect, useState } from 'react';
type Section='TOP'|'キャラクター'|'イラスト（上原）'|'イラスト（参加者）'|'相関図';
const nav:Section[]=['TOP','キャラクター','イラスト（上原）','イラスト（参加者）','相関図'];
type Artwork={title:string;src:string};
const artworks:Artwork[]=[];
const gifted:{name:string;src:string;url:string}[]=[];
const news=[['2026.08.28','志雲町立博物館の特設サイトを公開しました'],['2026.08.20','キャラクター紹介を追加しました'],['2026.08.12','展示イラストを更新しました']];
export default function Home(){
 const [section,setSection]=useState<Section>('TOP'),[detail,setDetail]=useState(false),[activating,setActivating]=useState(false),[art,setArt]=useState<Artwork|null>(null),[menu,setMenu]=useState(false);
 useEffect(()=>{window.scrollTo({top:0,behavior:'smooth'});setMenu(false)},[section,detail]);
 const openCharacter=()=>setDetail(true);
 return <><header className="site-header"><button className="brand" onClick={()=>{setSection('TOP');setDetail(false)}}>志雲町立博物館</button><button className="menu" aria-label="メニューを開く" onClick={()=>setMenu(!menu)}>MENU</button><nav className={menu?'open':''} aria-label="メインナビゲーション">{nav.map(item=><button key={item} className={section===item&&!detail?'active':''} onClick={()=>{setSection(item);setDetail(false)}}>{item}</button>)}</nav></header><main>
 {section==='TOP'&&<Top/>}
 {section==='キャラクター'&&(detail?<CharacterDetail onBack={()=>setDetail(false)}/>:<section className="page-section"><Heading en="CHARACTERS">キャラクター</Heading><p className="lead">志雲町立博物館に所属する学芸員をご紹介します。</p><div className="character-grid"><button className={`character-card ${activating?'activating':''}`} onClick={openCharacter}><span className="portrait-stack"><img className="normal" src="/images/chibi.png" alt="学芸員の仮画像"/><img className="hover" src="/images/hover.png" alt=""/></span><b>梓（あずさ）</b><small>植物標本担当</small></button></div></section>)}
 {section==='イラスト（上原）'&&<section className="page-section"><Heading en="GALLERY">イラスト（上原）</Heading><p className="lead">作品を選ぶと大きく表示されます。</p><div className="gallery">{artworks.map(item=><button key={item.src} onClick={()=>setArt(item)}><img src={item.src} alt={item.title}/><span>{item.title}</span></button>)}</div></section>}
 {section==='イラスト（参加者）'&&<section className="page-section"><Heading en="GUEST WORKS">イラスト（参加者）</Heading><p className="lead">描いていただいた作品へのリンク集です。</p><div className="guest-grid">{gifted.map(item=><a key={item.url} href={item.url} target="_blank" rel="noreferrer"><img src={item.src} alt=""/><div><b>{item.name} 様</b><span>Xで見る ↗</span></div></a>)}</div></section>}
 {section==='相関図'&&<Relationships/>}
 </main><footer><span>SHIUN MUNICIPAL MUSEUM</span><small>本サイトは架空の博物館を扱う一次創作サイトです。</small></footer>
 {art&&<div className="modal" role="dialog" aria-modal="true" aria-label={art.title} onClick={()=>setArt(null)}><button aria-label="閉じる">×</button><figure onClick={e=>e.stopPropagation()}><img src={art.src} alt={art.title}/><figcaption>{art.title}</figcaption></figure></div>}</>;
}
function Heading({en,children}:{en:string,children:React.ReactNode}){return <><p className="eyebrow">{en}</p><h1 className="page-title">{children}</h1></>}
function Top(){return <><section className="hero"><p className="eyebrow">SHIUN MUNICIPAL MUSEUM</p><h1>志雲町立<br/>博物館</h1><p className="hero-copy">青い鳥を探して</p></section><section className="panel"><p className="eyebrow">INTRODUCTION</p><h2>初めに</h2><p>志雲町立博物館は上原龍一郎による一次創作「愛館市立郷土資料館」の派生創作です。「愛館市立郷土資料館」の世界観を基盤とした相互限定のうちよそ企画となっています。</p><a href="https://aidate-museum.uehararyuichiro.workers.dev/" target="_blank" rel="noreferrer">「愛館市立郷土資料館」公式サイトを見る ↗</a></section><section className="panel"><p className="eyebrow">CURATOR</p><h2>学芸員とは</h2><p>博物館のスタッフです。</p><p>学芸員の見た目は担当の展示物と動物の要素が入ったものになっています。</p><p>学芸員は元々普通の人間です。死亡すると学芸員として雇用されます。</p><p>学芸員は歳をとりませんが、不死ではなく修復できない程の傷を受けると「破棄」となります。</p></section><section className="news"><div><p className="eyebrow">NEWS</p><h2>お知らせ</h2></div><div className="news-list">{news.map(([date,title])=><article key={title}><time>{date}</time><span>{title}</span></article>)}</div></section></>}
function CharacterDetail({onBack}:{onBack:()=>void}){const fields=[['性別','女性'],['身長','168cm'],['年齢','16歳'],['役職','志雲町立博物館　自然棟　植物標本担当'],['動物','エゾシカ'],['性格','元気なムードメーカー。少しおっちょこちょい'],['特技','寒さ、雪に強い'],['能力','「開花」\n植物の特性を増大させバフやデバフをかけることができる。手持ちの植物標本にない植物は使えない。'],['生い立ち','生前は平成～令和の比較的新しい時代に生きていた。死因は自死。'],['その他','現代の暮らしに関して仲間に教える立場。標本が劣化するのを嫌がり、頻繁に手入れをしている。']];return <section className="page-section"><button className="back" onClick={onBack}>← キャラクター一覧へ</button><div className="profile"><div className="profile-art"><img src="/images/hover.png" alt="梓（あずさ）"/></div><div><p className="eyebrow">SHIUMO CURATOR</p><h1 className="page-title">梓（あずさ）</h1><p className="lead">志雲町立博物館　自然棟　植物標本担当</p><dl>{fields.map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl></div></div><div className="panel"><p>可愛いものが好き。明るい性格で館内の空気を和ませる一方、植物標本の管理には人一倍こだわりを持っている。</p></div></section>}
function Relationships(){return <section className="page-section"><Heading en="RELATIONSHIPS">相関図</Heading><p className="lead">キャラクター同士のつながりを確認できます。</p><div className="relation-panel"><svg viewBox="0 0 100 100" preserveAspectRatio="none" aria-hidden="true"><path d="M50 18 L20 55 M50 18 L80 55 M20 55 L50 82 M80 55 L50 82"/><text x="22" y="34">一見怖そうだけど優しい</text><text x="58" y="34">一緒にいると落ち着く</text><text x="23" y="72">信頼</text><text x="68" y="72">仲間</text></svg><GraphNode x={50} y={15} name="梓"/><GraphNode x={18} y={55} name="丞"/><GraphNode x={82} y={55} name="汐音"/><GraphNode x={50} y={84} name="軍曹"/></div><p className="relation-note">※志雲町立博物館の正式なキャラクター設定に合わせて、名前・関係文は差し替えできます。</p></section>}
function GraphNode({x,y,name}:{x:number,y:number,name:string}){return <div className="graph-node" style={{left:`${x}%`,top:`${y}%`}}><img src="/images/chibi.png" alt=""/><b>{name}</b></div>}
